# Generated by Django 6.0.4 on 2026-06-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors',
            new_name='Doctor',
        ),
    ]
