# Generated by Django 6.0.4 on 2026-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_until',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', max_length=100),
        ),
    ]
