# Generated by Django 6.0.4 on 2026-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appointmentbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='patient_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
