# Generated by Django 6.0.4 on 2026-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_appointment_symptoms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentBooking',
        ),
    ]
