# Generated by Django 6.0.4 on 2026-09-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='break_end',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='break_start',
            field=models.TimeField(default='13:00'),
        ),
    ]
