# Generated by Django 6.0.4 on 2026-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_doctor_break_end_doctor_break_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
